name: Checks

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Build
        run: yarn build
